inherit_from: '.haml-lint_todo.yml'

linters:
  # Merging consecutive comments does not make the code clearer.
  # Instead it can make the indentation look quite weird.
  ConsecutiveComments:
    enabled: false

  # This warning is not always valid, and can break the code when multiple
  # interpolations are within a string.
  UnnecessaryStringOutput:
    enabled: false
