---

fallbacks: false

js_available_locales: ["en", "nl"]

export_i18n_js: false

translations:
  - file: "app/javascript/src/translations.js"
    prefix: "import I18n from 'i18n-js';\n"
    suffix: "export default I18n;\n"
    only:
      - "en"
      - "nl"
